//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/cvillaseca/SwiftViper
//

import UIKit

protocol ___FILEBASENAMEASIDENTIFIER___RouterInputProtocol: class {
    
}


class ___FILEBASENAMEASIDENTIFIER___Router: ___FILEBASENAMEASIDENTIFIER___RouterInputProtocol {
	
    weak var controller: UIViewController?
    
}